# Generated by Django 4.1.7 on 2023-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('date_birth', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('token', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=120)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
