# Generated by Django 4.1.7 on 2023-02-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, max_length=80, null=True)),
                ('token', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
